### ISSUE TITLE
MainLayout.js left unused?

### ISSUE THREAD

**Issue by hinell** [Zephir77167/ssr-starter-pack#4]
Where this [file](../tree/master/client/src/views/main-layout/js/MainLayout.js) is [used](../search?utf8=✓&q=MainLayout&type=) actually?
I know it is resembles (A)syncBundles but I didn't find place where it is imported.
Thanks.

**Comment by adrienharnay** [comment]
Hey, it is imported in [routes.js](https://github.com/Zephir77167/ssr-starter-pack/blob/master/client/src/entry/js/components/routes.js). As all Routes are children of the one with `component={MainLayout}`, it will be displayed on every page, and other Routes will be their `{children}`

**Comment by hinell** [comment]
Oh thanks, haven't spotted this initially.  👍

**Comment by adrienharnay** [comment]
All good, let me know if you got any more questions :)
